export enum ChildKey {
	Field = 'field',
	HelperText = 'helped-text',
	AppShell = 'app-shell',
	AppShellHeader = 'app-shell-header',
	AppShellSidebar = 'app-shell-sidebar',
	Card = 'card',
	CardHeader = 'card-header',
	CardBody = 'card-body',
	CardFooter = 'card-footer',
	Modal = 'modal',
	ModalHeader = 'modal-header',
	ModalBody = 'modal-body',
	ModalFooter = 'modal-footer',
}
