name: Zizmor

on:
  pull_request:
  push:
    branches: [main]

jobs:
  zizmor:
    name: Zizmor
    uses: immich-app/devtools/.github/workflows/shared-zizmor.yml@d6597891f4ae2a8ca157c4fe4fc04875ff34b9ea # main
    permissions:
      actions: read
      contents: read
      security-events: write
